install: 
	install /etc/hosts		root/etc/
	install jail.conf		/etc/jail.savvateev_app.conf
	install production.py		sourcecode/settings/production.py

uninstall:
	rm /etc/jail.savvateev_app.conf
	rm sourcecode/settings/production.py
	rm root/etc/resolv.conf
	rm root/etc/hosts
